[function.login]
image = "ghcr.io/evgnomon/salute"

[table.user]
in = "evgnomon/zygote/store/table/main"
id.type = "INT"
id.auto_increment = true
id.primary_key = true
password = "string"
email = "string"
inactive = "bool"
requires = ["timestamps"]
# created_at.type = "TIMESTAMP"
# created_at.default = "CURRENT_TIMESTAMP"
# updated_at.type = "TIMESTAMP"

# updated_at.default = "CURRENT_TIMESTAMP"
# updated_at.on_update = "CURRENT_TIMESTAMP"

[table.user.index]
unique = true
columns = ["email"]

### file: evgnomon/example-js-project/.zygote/main.toml:main
branches = ["main"]

[function.main]
in = "app"
image = "ghcr.io/evgnomon/example-js-project@main"
prefix = "example-js-project"
# max_instances = 1

[[function.main.mounts]]
source = "/var/run/docker.sock"
target = "/var/run/docker.sock"

[table.post]
in = "main"
requires = ["id", "timestamps"]
body = "json"
author = ["f:user"]                                # A foreign key to the user table
publisher = ["g:channel"]                          # A global foreign key
replies = ["g:channel"]                            # A global foreign key
# allow.io = ["main"]

[table.project]
in = "main"
requires = ["id", "timestamps"]
name = "string"
creator = ["f:user"]                        # A foreign keys
# allow.io = ["main"]

[table.channel]
in = "main"
includes = ["id", "timestamps"]
name = "string"
project = ["f:project"]                            # A foreign key
public = "bool"
# allow.io  = ["main"]

[[table.channel.index]]
unique = true
columns = ["name", "project"]

# Listen to posts
[stream.posts]
in = "main"
allow.io = ["main"]
